server:
  port: 8004
spring:
  application:
    name: @artifactId@
  cloud:
    stream:
      bindings:
        input:
          destination: jeecgCloudExchange #约定交换机通道名
          binder: local_rabbit
          group: jeecgCloudConsumers #指定分组名，解决重复消费问题
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 101.132.192.111
                port: 15672
                username: guest
                password: guest
                virtual-host: /
feign:
  sentinel:
    enabled: true
resttemplate:
  sentinel:
    enabled: true
